plugins {
    id 'java'
    id("xyz.jpenilla.run-paper") version "2.3.1"
}

group = 'lol.centrio.am.i'
version = '26.2-PRIVATE'

dependencies {
    compileOnly "io.papermc.paper:paper-api:26.2.build.+"
}

tasks {
    runServer {
        minecraftVersion("1.26.2")
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}
